/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-11 01:38:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>오직농구</title>\n");
      out.write("    <link href=\"./css/base.css?after\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"./css/common.css?after\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"./css/main.css?after\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    ");

        String user_id = null;
        if(session.getAttribute("user_id") != null) {
            user_id = (String) session.getAttribute("user_id");
        }
    
      out.write("\n");
      out.write("    <div id=\"wrap\">\n");
      out.write("        <!-- header -->\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <div id=\"gnb-top\" class=\"bg-season\"\n");
      out.write("                style=\"display: block; background: url('./images/logo.png') no-repeat center 0;\">\n");
      out.write("                <div class=\"gnb-fix-area\">\n");
      out.write("                    <h1 class=\"logo-link\"><a href=\"./main.jsp\">오직 농구 only basketball</a></h1>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- GNB -->\n");
      out.write("            <div id=\"gnb\">\n");
      out.write("                <ul id=\"menu\" class=\"gnb-list drop-menu\">\n");
      out.write("                    <li><a href=\"./popular.jsp\">오직인기</a></li>\n");
      out.write("                    <li><a href=\"./general.jsp\">오직컨텐츠</a></li>\n");
      out.write("                    <li><a href=\"./matching.jsp\">오직매칭</a></li>\n");
      out.write("                    <li><a href=\"./market.jsp\">오직거래</a></li>\n");
      out.write("                    <li><a href=\"./gym.jsp\">오직대관</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- //GNB -->\n");
      out.write("        </div>\n");
      out.write("        <!-- //header -->\n");
      out.write("\n");
      out.write("        <!-- container -->\n");
      out.write("        <div id=\"container\">\n");
      out.write("            <!-- 본문 -->\n");
      out.write("            <div id=\"content-wrap\">\n");
      out.write("                <!-- widget -->\n");
      out.write("                <div class=\"widget-wrap\">\n");
      out.write("                    <div class=\"widget\">\n");
      out.write("                        <h2><a href=\"./popular.jsp\">오직인기</a></h2>\n");
      out.write("                        <a href=\"./popular.jsp\" class=\"widget-more\">+</a>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"item-wrap\">\n");
      out.write("									<span class=\"title-wrap\"><span class=\"date\">2022-09-08</span>\n");
      out.write("                                    <a href=\"/view/11438096795\" class=\"title\">test제목</a></span>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"widget widget-right\">\n");
      out.write("                        <h2><a href=\"./general.jsp\">오직컨텐츠</a></h2>\n");
      out.write("                        <a href=\"./general.jsp\" class=\"widget-more\">+</a>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"item-wrap\">\n");
      out.write("                                	<span class=\"title-wrap\">\n");
      out.write("                                		<span class=\"date\">2022-09-08</span>\n");
      out.write("                                		<a href=\"/view/11438106259\" class=\"title\">test제목</a>\n");
      out.write("                                		</span>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    </div>           \n");
      out.write("                    <div class=\"widget\">\n");
      out.write("                        <h2><a href=\"./popular.jsp\">오직거래</a></h2>\n");
      out.write("                        <a href=\"./popular.jsp\" class=\"widget-more\">+</a>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"item-wrap\">\n");
      out.write("									<span class=\"title-wrap\"><span class=\"date\">2022-09-08</span>\n");
      out.write("                                    <a href=\"/view/11438096795\" class=\"title\">test제목</a></span>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"widget widget-right\">\n");
      out.write("                        <h2><a href=\"./general.jsp\">오직대관</a></h2>\n");
      out.write("                        <a href=\"./general.jsp\" class=\"widget-more\">+</a>\n");
      out.write("                        <ul>\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"item-wrap\">\n");
      out.write("                                	<span class=\"title-wrap\">\n");
      out.write("                                		<span class=\"date\">2022-09-08</span>\n");
      out.write("                                		<a href=\"/view/11438106259\" class=\"title\">test제목</a>\n");
      out.write("                                		</span>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("\n");
      out.write("                        </ul>\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- //본문 -->\n");
      out.write("            <!-- aside -->\n");
      out.write("            <div id=\"aside-wrap\">\n");
      out.write("                <div id=\"rightside\">\n");
      out.write("                    ");

                        if(user_id == null) {
                    
      out.write("\n");
      out.write("                    <div class=\"login-wrap\">\n");
      out.write("                        <form id=\"loginForm\" method=\"post\" action=\"./loginAction.jsp\" accept-charset=\"utf-8\">\n");
      out.write("                            <div class=\"login-box\">\n");
      out.write("                                <span>\n");
      out.write("                                    <input type=\"text\" name=\"user_id\" placeholder=\"아이디\" >\n");
      out.write("                                    <input type=\"password\" name=\"password\" placeholder=\"비밀번호\">\n");
      out.write("                                </span>\n");
      out.write("                                <button type=\"submit\" value=\"main\" name=\"loginButton\">\n");
      out.write("                                    <span>로그인</span>\n");
      out.write("                                </button>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                        <div class=\"user-util\">\n");
      out.write("                            <a href=\"/join.jsp\">회원가입</a>\n");
      out.write("                            <a href=\"/member/find/id\">아이디·비밀번호 찾기</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    ");

                        } else {
                    
      out.write("\n");
      out.write("                    <div class=\"logout-wrap\">\n");
      out.write("                            <div class=\"logout-box\">\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 정보</button><br>\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 팀 정보</button><br>\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">로그아웃</button>\n");
      out.write("                            </div>\n");
      out.write("                    </div>\n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("                    <!-- //login -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- aside 끝 -->\n");
      out.write("        </div>\n");
      out.write("        <!-- //container -->\n");
      out.write("\n");
      out.write("        <!-- footer -->\n");
      out.write("        <div id=\"footer\">\n");
      out.write("        </div>\n");
      out.write("        <!-- //footer -->\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
