/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-12-11 01:41:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class makeHomeGame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>오직농구</title>\r\n");
      out.write("	<link href=\"./css/base.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/common.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/main.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/board.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/mypage.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <script>\r\n");
      out.write("        function chooseForm(radioname) {\r\n");
      out.write("            var radios = document.getElementsByName(radioname);\r\n");
      out.write("            for(var i = 0, length = radios.length; i < length; i++) {\r\n");
      out.write("                document.getElementById(radios[i].value + '-form').style.display = 'none';\r\n");
      out.write("                if(radios[i].checked) {\r\n");
      out.write("                    document.getElementById(radios[i].value + '-form').style.display = 'block';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function goPopup(game){\r\n");
      out.write("            // 주소검색을 수행할 팝업 페이지를 호출합니다.\r\n");
      out.write("            // 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(https://business.juso.go.kr/addrlink/addrLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("            var pop = window.open(\"/jusoPopup.jsp?id=\"+game,\"pop\",\"width=570,height=420, scrollbars=yes, resizable=yes\"); \r\n");
      out.write("            \r\n");
      out.write("            // 모바일 웹인 경우, 호출된 페이지(jusopopup.jsp)에서 실제 주소검색URL(https://business.juso.go.kr/addrlink/addrMobileLinkUrl.do)를 호출하게 됩니다.\r\n");
      out.write("            //var pop = window.open(\"/popup/jusoPopup.jsp\",\"pop\",\"scrollbars=yes, resizable=yes\"); \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function jusoCallBack(roadAddrPart1){\r\n");
      out.write("            // 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("            document.form.roadAddrPart1.value = roadAddrPart1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function pickup_jusoCallBack(roadAddrPart1){\r\n");
      out.write("            // 팝업페이지에서 주소입력한 정보를 받아서, 현 페이지에 정보를 등록합니다.\r\n");
      out.write("            document.pickup_form.roadAddrPart1.value = roadAddrPart1;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        String user_id = null;
        if(session.getAttribute("user_id") != null) {
            user_id = (String) session.getAttribute("user_id");
        }
    
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("        <!-- header -->\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"gnb-top\" class=\"bg-season\"\r\n");
      out.write("                style=\"display: block; background: url('./images/logo.png') no-repeat center 0;\">\r\n");
      out.write("                <div class=\"gnb-fix-area\">\r\n");
      out.write("                    <h1 class=\"logo-link\"><a href=\"./main.jsp\">오직 농구 only basketball</a></h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- GNB -->\r\n");
      out.write("            <div id=\"gnb\">\r\n");
      out.write("                <ul id=\"menu\" class=\"gnb-list drop-menu\">\r\n");
      out.write("                    <li><a href=\"./popular.jsp\">오직인기</a></li>\r\n");
      out.write("                    <li><a href=\"./general.jsp\">오직컨텐츠</a></li>\r\n");
      out.write("                    <li><a href=\"./matching.jsp\">오직매칭</a></li>\r\n");
      out.write("                    <li><a href=\"./market.jsp\">오직거래</a></li>\r\n");
      out.write("                    <li><a href=\"./gym.jsp\">오직대관</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //GNB -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //header -->\r\n");
      out.write("        <!-- container -->\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            <!-- 본문 -->\r\n");
      out.write("            <div id=\"content-wrap\">\r\n");
      out.write("                <div class=\"account-body\" id=\"step_2\">\r\n");
      out.write("                    <div id=\"game-making-button\">\r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-away\" onclick=\"chooseForm(this.name)\" checked=\"checked\">어웨이팀을 원해요\r\n");
      out.write("                        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp \r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-guest\" onclick=\"chooseForm(this.name)\">게스트를 원해요\r\n");
      out.write("                        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp \r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-pickup\" onclick=\"chooseForm(this.name)\">픽업게임 만들기\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 어웨이팀을 원해요 폼 시작 -->\r\n");
      out.write("                    <form id=\"want-away-form\" name=\"form\" method=\"post\" action=\"homeWantAwayAction.jsp\" >\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <input type=\"text\" name=\"home_id\" style=\"display: none;\" value=\"");
      out.print(user_id);
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">내 팀 이름</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <span class=\"item-value modify-on\">\r\n");
      out.write("                                        <input type=\"text\" name=\"h_team_name\" placeholder=\"팀이름을 입력하세요\">\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <span class=\"item-value modify-on\">\r\n");
      out.write("                                        <input type=\"text\" id=\"roadAddrPart1\" name=\"roadAddrPart1\" readonly>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <button type=\"button\" id=\"juso-search\" class=\"juso-search\" value=\"away\" onclick=\"goPopup(this.value)\">\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <em>주소 검색</em>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <input type=\"datetime-local\" name=\"date\" id=\"game_date_time\" >\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_people\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"5people\">5명</option>\r\n");
      out.write("                                        <option value=\"6people\">6명</option>\r\n");
      out.write("                                        <option value=\"7people\">7명</option>\r\n");
      out.write("                                        <option value=\"8people\">8명</option>\r\n");
      out.write("                                        <option value=\"9people\">9명</option>\r\n");
      out.write("                                        <option value=\"10people\">10명</option>\r\n");
      out.write("                                        <option value=\"11people\">11명</option>\r\n");
      out.write("                                        <option value=\"12people\">12명</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_age\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"late_10dae\">10대 후반</option>\r\n");
      out.write("                                        <option value=\"early_20dae\">20대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_20dae\">20대 중반</option>\r\n");
      out.write("                                        <option value=\"late_20dae\">20대 후반</option>\r\n");
      out.write("                                        <option value=\"early_30dae\">30대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_30dae\">30대 중반</option>\r\n");
      out.write("                                        <option value=\"late_30dae\">30대 후반</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 유니폼 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_uniform\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"red\">빨강</option>\r\n");
      out.write("                                        <option value=\"blue\">파랑</option>\r\n");
      out.write("                                        <option value=\"black\">검정</option>\r\n");
      out.write("                                        <option value=\"white\">하양</option>\r\n");
      out.write("                                        <option value=\"yellow\">노랑</option>\r\n");
      out.write("                                        <option value=\"green\">초록</option>\r\n");
      out.write("                                        <option value=\"pink\">분홍</option>\r\n");
      out.write("                                        <option value=\"orange\">주황</option>\r\n");
      out.write("                                        <option value=\"purple\">보라</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_people\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"5people\">5명</option>\r\n");
      out.write("                                        <option value=\"6people\">6명</option>\r\n");
      out.write("                                        <option value=\"7people\">7명</option>\r\n");
      out.write("                                        <option value=\"8people\">8명</option>\r\n");
      out.write("                                        <option value=\"9people\">9명</option>\r\n");
      out.write("                                        <option value=\"10people\">10명</option>\r\n");
      out.write("                                        <option value=\"11people\">11명</option>\r\n");
      out.write("                                        <option value=\"12people\">12명</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 실력</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_level\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"S\">S</option>\r\n");
      out.write("                                        <option value=\"A\">A</option>\r\n");
      out.write("                                        <option value=\"B\">B</option>\r\n");
      out.write("                                        <option value=\"C\">C</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_age\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"late_10dae\">10대 후반</option>\r\n");
      out.write("                                        <option value=\"early_20dae\">20대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_20dae\">20대 중반</option>\r\n");
      out.write("                                        <option value=\"late_20dae\">20대 후반</option>\r\n");
      out.write("                                        <option value=\"early_30dae\">30대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_30dae\">30대 중반</option>\r\n");
      out.write("                                        <option value=\"late_30dae\">30대 후반</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"shower\" value=\"shower_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"shower\" value=\"shower_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                 <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"parking\" value=\"parking_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"parking\" value=\"parking_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <textarea name=\"warning\" cols=\"40\" rows=\"4\"></textarea>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- 어웨이팀을 원해요 폼 끝 -->\r\n");
      out.write("                    <!-- 게스트를 원해요 폼 시작 -->\r\n");
      out.write("                    <form id=\"want-guest-form\" method=\"post\" action=\"GameWantAwayAction.jsp\">\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <input type=\"text\" name=\"home_id\" style=\"display: none;\" value=\"");
      out.print(user_id);
      out.write("\">\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <span class=\"item-value modify-on\">\r\n");
      out.write("                                        <input type=\"text\" id=\"pickup_juso\" name=\"pickup_juso\" readonly>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <button type=\"button\" id=\"juso-search\" class=\"juso-search\" onclick=\"pickup_goPopup()\">\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <em>주소 검색</em>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <input type=\"datetime-local\" name=\"game_date_time\" id=\"game_date_time\" >\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_people_count\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"5people\">5명</option>\r\n");
      out.write("                                        <option value=\"6people\">6명</option>\r\n");
      out.write("                                        <option value=\"7people\">7명</option>\r\n");
      out.write("                                        <option value=\"8people\">8명</option>\r\n");
      out.write("                                        <option value=\"9people\">9명</option>\r\n");
      out.write("                                        <option value=\"10people\">10명</option>\r\n");
      out.write("                                        <option value=\"11people\">11명</option>\r\n");
      out.write("                                        <option value=\"12people\">12명</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_age\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"late_10dae\">10대 후반</option>\r\n");
      out.write("                                        <option value=\"early_20dae\">20대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_20dae\">20대 중반</option>\r\n");
      out.write("                                        <option value=\"late_20dae\">20대 후반</option>\r\n");
      out.write("                                        <option value=\"early_30dae\">30대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_30dae\">30대 중반</option>\r\n");
      out.write("                                        <option value=\"late_30dae\">30대 후반</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 유니폼 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"home_uniform\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"red\">빨강</option>\r\n");
      out.write("                                        <option value=\"blue\">파랑</option>\r\n");
      out.write("                                        <option value=\"black\">검정</option>\r\n");
      out.write("                                        <option value=\"white\">하양</option>\r\n");
      out.write("                                        <option value=\"yellow\">노랑</option>\r\n");
      out.write("                                        <option value=\"green\">초록</option>\r\n");
      out.write("                                        <option value=\"pink\">분홍</option>\r\n");
      out.write("                                        <option value=\"orange\">주황</option>\r\n");
      out.write("                                        <option value=\"purple\">보라</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_people_count\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"5people\">5명</option>\r\n");
      out.write("                                        <option value=\"6people\">6명</option>\r\n");
      out.write("                                        <option value=\"7people\">7명</option>\r\n");
      out.write("                                        <option value=\"8people\">8명</option>\r\n");
      out.write("                                        <option value=\"9people\">9명</option>\r\n");
      out.write("                                        <option value=\"10people\">10명</option>\r\n");
      out.write("                                        <option value=\"11people\">11명</option>\r\n");
      out.write("                                        <option value=\"12people\">12명</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 실력</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_people_count\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"S\">S</option>\r\n");
      out.write("                                        <option value=\"A\">A</option>\r\n");
      out.write("                                        <option value=\"B\">B</option>\r\n");
      out.write("                                        <option value=\"C\">C</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"away_age\" form=\"want-away-form\">\r\n");
      out.write("                                        <option value=\"late_10dae\">10대 후반</option>\r\n");
      out.write("                                        <option value=\"early_20dae\">20대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_20dae\">20대 중반</option>\r\n");
      out.write("                                        <option value=\"late_20dae\">20대 후반</option>\r\n");
      out.write("                                        <option value=\"early_30dae\">30대 초반</option>\r\n");
      out.write("                                        <option value=\"middle_30dae\">30대 중반</option>\r\n");
      out.write("                                        <option value=\"late_30dae\">30대 후반</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"can_shower\" value=\"shower_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"can_shower\" value=\"shower_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                 <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"can_parking\" value=\"parking_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"can_parking\" value=\"parking_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <textarea name=\"warning\" cols=\"40\" rows=\"4\">\r\n");
      out.write("                                </textarea>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- 게스트를 원해요 폼 끝 -->\r\n");
      out.write("                    <!-- 픽업게임을 원해요 폼 시작 -->\r\n");
      out.write("                    <form id=\"want-pickup-form\" name=\"pickup_form\" method=\"post\" action=\"makePickupAction.jsp\">\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <input type=\"text\" name=\"home_id\" style=\"display: none;\" value=\"");
      out.print(user_id);
      out.write("\">\r\n");
      out.write("                            \r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <span class=\"item-value modify-on\">\r\n");
      out.write("                                        <input type=\"text\" id=\"roadAddrPart1\" name=\"roadAddrPart1\" readonly>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <button type=\"button\" id=\"juso-search\" class=\"juso-search\" value=\"pickup\" onclick=\"goPopup(this.value)\">\r\n");
      out.write("                                        <span>\r\n");
      out.write("                                            <em>주소 검색</em>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <input type=\"datetime-local\" name=\"date\" id=\"game_date_time\" >\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 게스트 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"people\" form=\"want-pickup-form\">\r\n");
      out.write("                                        <option value=\"11people\">11명</option>\r\n");
      out.write("                                        <option value=\"12people\">12명</option>\r\n");
      out.write("                                        <option value=\"13people\">13명</option>\r\n");
      out.write("                                        <option value=\"14people\">14명</option>\r\n");
      out.write("                                        <option value=\"15people\">15명</option>\r\n");
      out.write("                                        <option value=\"16people\">16명</option>\r\n");
      out.write("                                        <option value=\"17people\">17명</option>\r\n");
      out.write("                                        <option value=\"18people\">18명</option>\r\n");
      out.write("                                        <option value=\"19people\">19명</option>\r\n");
      out.write("                                        <option value=\"20people\">20명</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">게임 수준</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"level\" form=\"want-pickup-form\">\r\n");
      out.write("                                        <option value=\"S\">S</option>\r\n");
      out.write("                                        <option value=\"A\">A</option>\r\n");
      out.write("                                        <option value=\"B\">B</option>\r\n");
      out.write("                                        <option value=\"C\">C</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">게스트 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"age\" form=\"want-pickup-form\">\r\n");
      out.write("                                        <option value=\"every\">관계없음</option>\r\n");
      out.write("                                        <option value=\"20dae\">20대</option>\r\n");
      out.write("                                        <option value=\"30dae\">30대</option>\r\n");
      out.write("                                        <option value=\"40dae\">40대</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">운동복 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                    <select class=\"select-box\" name=\"color\" form=\"want-pickup-form\">\r\n");
      out.write("                                        <option value=\"BandW\">검정/하양</option>\r\n");
      out.write("                                        <option value=\"RandB\">빨강/파랑</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"can_shower\" value=\"shower_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"can_shower\" value=\"shower_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                 <dd class=\"radio\">\r\n");
      out.write("                                <input type=\"radio\" name=\"can_parking\" value=\"parking_yes\">유\r\n");
      out.write("                                &nbsp &nbsp \r\n");
      out.write("                                <input type=\"radio\" name=\"can_parking\" value=\"parking_no\">무\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <textarea name=\"warning\" cols=\"40\" rows=\"4\"></textarea>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- 픽업게임을 원해요 폼 끝 -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 본문 끝-->           \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- aside 시작 -->\r\n");
      out.write("            <div id=\"aside-wrap\">\r\n");
      out.write("                <div id=\"rightside\">\r\n");
      out.write("                    ");

                        if(user_id == null) {
                    
      out.write("\r\n");
      out.write("                    <div class=\"login-wrap\">\r\n");
      out.write("                        <form id=\"loginForm\" method=\"post\" action=\"loginAction.jsp\" accept-charset=\"utf-8\">\r\n");
      out.write("                            <div class=\"login-box\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <input type=\"text\" name=\"user_id\" placeholder=\"아이디\" >\r\n");
      out.write("                                    <input type=\"password\" name=\"password\" placeholder=\"비밀번호\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <button type=\"submit\"><span>로그인</span></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"user-util\">\r\n");
      out.write("                            <a href=\"/join.jsp\">회원가입</a>\r\n");
      out.write("                            <a href=\"/member/find/id\">아이디·비밀번호 찾기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        } else {
                    
      out.write("\r\n");
      out.write("                    <div class=\"logout-wrap\">\r\n");
      out.write("                            <div class=\"logout-box\">\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 정보</button><br>\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 팀 정보</button><br>\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">로그아웃</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                    <!-- //login -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- aside 끝 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //container -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer -->\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //footer -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
