/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-11-28 07:08:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class makeHomeGame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>오직농구</title>\r\n");
      out.write("	<link href=\"./css/base.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/common.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/main.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/board.css?after\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"./css/mypage.css?after\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");

        String user_id = null;
        if(session.getAttribute("user_id") != null) {
            user_id = (String) session.getAttribute("user_id");
        }
    
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("        <!-- header -->\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"gnb-top\" class=\"bg-season\"\r\n");
      out.write("                style=\"display: block; background: url('./images/logo.png') no-repeat center 0;\">\r\n");
      out.write("                <div class=\"gnb-fix-area\">\r\n");
      out.write("                    <h1 class=\"logo-link\"><a href=\"./main.jsp\">오직 농구 only basketball</a></h1>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- GNB -->\r\n");
      out.write("            <div id=\"gnb\">\r\n");
      out.write("                <ul id=\"menu\" class=\"gnb-list drop-menu\">\r\n");
      out.write("                    <li><a href=\"./popular.jsp\">오직인기</a></li>\r\n");
      out.write("                    <li><a href=\"./general.jsp\">오직컨텐츠</a></li>\r\n");
      out.write("                    <li><a href=\"./matching.jsp\">오직매칭</a></li>\r\n");
      out.write("                    <li><a href=\"./market.jsp\">오직거래</a></li>\r\n");
      out.write("                    <li><a href=\"./gym.jsp\">오직대관</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- //GNB -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //header -->\r\n");
      out.write("        <!-- container -->\r\n");
      out.write("        <div id=\"container\">\r\n");
      out.write("            <!-- 본문 -->\r\n");
      out.write("            <div id=\"content-wrap\">\r\n");
      out.write("                <script>\r\n");
      out.write("                    function chooseForm(radioname) {\r\n");
      out.write("                        var radios = document.getElementsByName(radioname);\r\n");
      out.write("                        for(var i = 0, length = radios.length; i < length; i++) {\r\n");
      out.write("                            document.getElementById(radios[i].value + '-form').style.display = 'none';\r\n");
      out.write("                            if(radios[i].checked) {\r\n");
      out.write("                                document.getElementById(radios[i].value + '-form').style.display = 'block';\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("                <div class=\"account-body\" id=\"step_2\">\r\n");
      out.write("                    <div id=\"game-making-button\">\r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-away\" onclick=\"chooseForm(this.name)\" checked=\"checked\">어웨이팀을 원해요\r\n");
      out.write("                        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp \r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-guest\" onclick=\"chooseForm(this.name)\">게스트를 원해요\r\n");
      out.write("                        &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp \r\n");
      out.write("                        <input type=\"radio\" name=\"which-game\" value=\"want-pickup\" onclick=\"chooseForm(this.name)\">픽업게임 만들기\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <form id=\"want-away-form\" method=\"post\" action=\"GameWantAwayAction.jsp\" >\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"location\" id=\"location\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"game_date\" id=\"game_date\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_member_count\" id=\"home_member_count\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_age\" id=\"home_age\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 유니폼 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_uniform\" id=\"home_uniform\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"away_member_count\" id=\"away_member_count\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 실력</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"away_level\" id=\"away_level\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 어웨이 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"away_age\" id=\"away_age\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"shower\" id=\"shower\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"parking\" id=\"parking\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"warning\" id=\"warning\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form id=\"want-guest-form\" method=\"post\" action=\"GameWantAwayAction.jsp\">\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"location\" id=\"location\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"game_date\" id=\"game_date\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_member_count\" id=\"home_member_count\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_age\" id=\"home_age\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">홈 팀 유니폼 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"home_uniform\" id=\"home_uniform\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 게스트 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"guest_member_count\" id=\"guest_member_count\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 게스트 포지션</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"guest_position\" id=\"guest_position\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">바라는 게스트 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"guest_age\" id=\"guest_age\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"shower\" id=\"shower\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"parking\" id=\"parking\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"warning\" id=\"warning\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <form id=\"want-pickup-form\" method=\"post\" action=\"GameWantAwayAction.jsp\">\r\n");
      out.write("                        <div class=\"section\">\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 장소</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"location\" id=\"location\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">시합 날짜 및 시간</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"game_date\" id=\"game_date\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">게스트 인원</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"guest_member_count\" id=\"guest_member_count\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">게스트 나이대</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"guest_age\" id=\"guest_age\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">유니폼 색상</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"uniform_color\" id=\"uniform_color\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">샤워 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"shower\" id=\"shower\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">주차 시설</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"parking\" id=\"parking\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <dl class=\"make-game-info\">\r\n");
      out.write("                                <dt class=\"essential\">기타 주의 사항</dt>\r\n");
      out.write("                                <dd>\r\n");
      out.write("                                <span class=\"item-value modify-on\">\r\n");
      out.write("                                <input type=\"text\" name=\"warning\" id=\"warning\" placeholder=\"\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                </dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--버튼-->\r\n");
      out.write("                        <div class=\"btn-wrap\">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn-orange-big\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <em>등록</em>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 본문 끝-->           \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- aside 시작 -->\r\n");
      out.write("            <div id=\"aside-wrap\">\r\n");
      out.write("                <div id=\"rightside\">\r\n");
      out.write("                    ");

                        if(user_id == null) {
                    
      out.write("\r\n");
      out.write("                    <div class=\"login-wrap\">\r\n");
      out.write("                        <form id=\"loginForm\" method=\"post\" action=\"loginAction.jsp\" accept-charset=\"utf-8\">\r\n");
      out.write("                            <div class=\"login-box\">\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <input type=\"text\" name=\"user_id\" placeholder=\"아이디\" >\r\n");
      out.write("                                    <input type=\"password\" name=\"password\" placeholder=\"비밀번호\">\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <button type=\"submit\"><span>로그인</span></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"user-util\">\r\n");
      out.write("                            <a href=\"/join.jsp\">회원가입</a>\r\n");
      out.write("                            <a href=\"/member/find/id\">아이디·비밀번호 찾기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        } else {
                    
      out.write("\r\n");
      out.write("                    <div class=\"logout-wrap\">\r\n");
      out.write("                            <div class=\"logout-box\">\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 정보</button><br>\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">내 팀 정보</button><br>\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='./logoutAction.jsp'\">로그아웃</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    ");

                        }
                    
      out.write("\r\n");
      out.write("                    <!-- //login -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- aside 끝 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //container -->\r\n");
      out.write("\r\n");
      out.write("        <!-- footer -->\r\n");
      out.write("        <div id=\"footer\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- //footer -->\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
